-- Create blog_posts table for SEO-optimized blog content
CREATE TABLE IF NOT EXISTS blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  startup_id UUID NOT NULL REFERENCES startups(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  excerpt TEXT,
  meta_description TEXT,
  keywords TEXT[],
  author_name TEXT DEFAULT 'SubmitHunt Team',
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  view_count INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  generated_by TEXT DEFAULT 'template', -- 'openai' or 'template'
  
  -- Indexes for performance
  CONSTRAINT blog_posts_startup_id_unique UNIQUE(startup_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_blog_posts_startup_id ON blog_posts(startup_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_published ON blog_posts(is_published);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_blog_posts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER blog_posts_updated_at
  BEFORE UPDATE ON blog_posts
  FOR EACH ROW
  EXECUTE FUNCTION update_blog_posts_updated_at();

-- Enable RLS
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Blog posts are viewable by everyone"
  ON blog_posts FOR SELECT
  USING (is_published = true);

CREATE POLICY "Blog posts are insertable by service role"
  ON blog_posts FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Blog posts are updatable by service role"
  ON blog_posts FOR UPDATE
  USING (true);

-- Add comment
COMMENT ON TABLE blog_posts IS 'SEO-optimized blog posts generated for each startup listing';
COMMENT ON COLUMN blog_posts.generated_by IS 'Indicates whether the post was generated by OpenAI or template fallback';
