name: Daily Live Notifications

on:
  schedule:
    # Run at 8:00 AM PST (15:00 UTC to account for PST/PDT)
    - cron: '0 15 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send Live Notifications
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://lbayphzxmdtdmrqmeomt.supabase.co/functions/v1/send-live-notifications)
          
          http_code="${response: -3}"
          body="${response%???}"
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          fi
      
      - name: Log Results
        if: always()
        run: |
          echo "Daily notification job completed at $(date)"
